version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: r123
      MYSQL_DATABASE: TestDB
      MYSQL_USER: user
      MYSQL_PASSWORD: p123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
